"""add_signal_data_to_trades

Revision ID: 25e371346f7a
Revises: 77f3d5686713
Create Date: 2026-02-20 12:31:16.082496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e371346f7a'
down_revision: Union[str, None] = '77f3d5686713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signal_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'signal_data')
    # ### end Alembic commands ###
