"""add_equity_prices_table

Revision ID: 53e69f29a2ff
Revises: b1d92df9b834
Create Date: 2026-03-08 22:59:30.041060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e69f29a2ff'
down_revision: Union[str, None] = 'b1d92df9b834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_prices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('symbol', sa.String(length=50), nullable=False),
        sa.Column('datetime', sa.DateTime(), nullable=False),
        sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('volume', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('symbol', 'datetime', name='uq_equity_price')
    )
    op.create_index(op.f('ix_equity_prices_datetime'), 'equity_prices', ['datetime'], unique=False)
    op.create_index(op.f('ix_equity_prices_symbol'), 'equity_prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equity_prices_symbol'), table_name='equity_prices')
    op.drop_index(op.f('ix_equity_prices_datetime'), table_name='equity_prices')
    op.drop_table('equity_prices')
    # ### end Alembic commands ###
