"""add_equity_prices_table

Revision ID: 53e69f29a2ff
Revises: b1d92df9b834
Create Date: 2026-03-08 22:59:30.041060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e69f29a2ff'
down_revision: Union[str, None] = 'b1d92df9b834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
