"""Add NiftyCandle model

Revision ID: b1d92df9b834
Revises: 25e371346f7a
Create Date: 2026-03-02 10:23:23.026673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d92df9b834'
down_revision: Union[str, None] = '25e371346f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nifty_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_nifty_candle')
    )
    op.create_index(op.f('ix_nifty_candles_interval'), 'nifty_candles', ['interval'], unique=False)
    op.create_index(op.f('ix_nifty_candles_symbol'), 'nifty_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_nifty_candles_timestamp'), 'nifty_candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nifty_candles_timestamp'), table_name='nifty_candles')
    op.drop_index(op.f('ix_nifty_candles_symbol'), table_name='nifty_candles')
    op.drop_index(op.f('ix_nifty_candles_interval'), table_name='nifty_candles')
    op.drop_table('nifty_candles')
    # ### end Alembic commands ###
